version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/
permissions:
  - object: /home/ubuntu/app/
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall
    - location: code_deploy_scripts/predeploy.sh
  ApplicationStart
    - location: code_deploy_scripts/postdeploy.sh